- name: Install dep apt package
  apt:
    name: go-dep
  become: yes
  become_method: sudo
  become_user: root

- name: Add golang plugin to asdf
  command: "${HOME}/.asdf/bin/asdf plugin-add golang"
  register: golang_add
  failed_when: golang_add == 2

- name: Install golang {{go_version}} with asdf
  command: "${HOME}/.asdf/bin/asdf install golang {{go_version}}"

- name: Set global version for golang to {{go_version}}
  command: "${HOME}/.asdf/bin/asdf global golang {{go_version}}"
