- name: Upgrade apt
  apt: upgrade=yes
  when: 
    - not ansible_check_mode
    - package_upgrade
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages }}"
  when: not ansible_check_mode


- name: Remove apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: absent
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ remove_packages }}"
  when: not ansible_check_mode

- name: Create ~/.local/bin directory for bat
  file:
    path: "{{ dotfiles_user_home }}/.local/bin"
    state: directory

- name: Add bat symlink to repoint from batcat
  file:
    src: "/usr/bin/batcat"
    dest: "{{ dotfiles_user_home }}/.local/bin/bat"
    state: link

- name: Add custom Regolith Xresources
  file:
    src: "{{ dotfiles_home }}/roles/apt/files/Xresources"
    dest: "{{ dotfiles_user_home }}/.config/regolith/Xresources"
    state: link

- name: Check for presence of the custom Regolith config
  stat: path="{{ dotfiles_user_home }}/.config/regolith/i3/config"
  register: basic_regolith_config

- name: Copy basic Regolith config file
  command: "cp /etc/regolith/i3/config {{ dotfiles_user_home }}/.config/regolith/i3/config"
  args:
    creates: "{{ dotfiles_user_home }}/.config/regolith/i3/config"
  when: not basic_regolith_config.stat.exists

- name: Link additional config settings
  blockinfile:
    block: "{{ lookup('file', '~/.dotfiles/roles/apt/files/config') }}"
    path: "{{ dotfiles_user_home }}/.config/regolith/i3/config"

- name: Link fdfind to fd
  file:
    src: "/usr/bin/fdfind"
    dest: "{{ dotfiles_user_home }}/.local/bin/fd"
    state: link
