- name: Install zsh
  apt: name=zsh state=present
  become: yes
  become_user: root
  become_method: sudo

- name: Check for oh-my-zsh installation
  stat: "path=~/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh
  raw: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
  when: not oh_my_zsh_stat.stat.exists

- name: Check for .zshrc
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up .zshrc
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Remove .zshrc
  command: rm ~/.zshrc
  when: zshrc_stat.stat.exists


- name: Symlink .zshrc
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/zshrc"
    dest: "{{dotfiles_user_home}}/.zshrc"
    state: link
