- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{dotfiles_user_home}}/.tmux/plugins/tpm"

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link
