- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

# TODO: Fedora

- name: Install tmuxp with pipx
  command: "pipx install --force tmuxp"
  args:
    creates: "{{dotfiles_user_home}}/.local/pipx/venvs/tmuxp"
  when: tmux_install_tmuxp
  tags:
    - pipx

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{dotfiles_user_home}}/.tmux/plugins/tpm"

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf"
    dest: "{{dotfiles_user_home}}/.tmux.conf"
    state: link
