- name: Add ruby plugin
  command: "asdf plugin-add ruby"
  register: ruby_add
  failed_when: ruby_add == 2

- name: "Install ruby versions"
  command: asdf install ruby {{item}}
  loop: "{{versions}}"

- name: Set global version for ruby to {{versions[0]}}
  command: "asdf global ruby {{versions[0]}}"
